wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683809939.318816
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 77
      3:
      - 1
      - 7
      - 13
      - 15
      - 23
      4: 3.8.10
      5: 0.15.1
      8:
      - 3
      - 8
    m:
    - 1: trainer/global_step
      6:
      - 3
data/root_path:
  desc: null
  value: C:\Users\GrzegorzKaszuba\PycharmProjects\cdvae-main/data/perov_5
data/prop:
  desc: null
  value: heat_ref
data/num_targets:
  desc: null
  value: 1
data/niggli:
  desc: null
  value: true
data/primitive:
  desc: null
  value: false
data/graph_method:
  desc: null
  value: crystalnn
data/lattice_scale_method:
  desc: null
  value: scale_length
data/preprocess_workers:
  desc: null
  value: 4
data/readout:
  desc: null
  value: mean
data/max_atoms:
  desc: null
  value: 20
data/otf_graph:
  desc: null
  value: false
data/eval_model_name:
  desc: null
  value: perovskite
data/train_max_epochs:
  desc: null
  value: 5
data/early_stopping_patience:
  desc: null
  value: 100000
data/teacher_forcing_max_epoch:
  desc: null
  value: 1500
data/datamodule/_target_:
  desc: null
  value: cdvae.pl_data.datamodule.CrystDataModule
data/datamodule/datasets/train/_target_:
  desc: null
  value: cdvae.pl_data.dataset.CrystDataset
data/datamodule/datasets/train/name:
  desc: null
  value: Formation energy train
data/datamodule/datasets/train/path:
  desc: null
  value: C:\Users\GrzegorzKaszuba\PycharmProjects\cdvae-main/data/perov_5/train.csv
data/datamodule/datasets/train/prop:
  desc: null
  value: heat_ref
data/datamodule/datasets/train/niggli:
  desc: null
  value: true
data/datamodule/datasets/train/primitive:
  desc: null
  value: false
data/datamodule/datasets/train/graph_method:
  desc: null
  value: crystalnn
data/datamodule/datasets/train/lattice_scale_method:
  desc: null
  value: scale_length
data/datamodule/datasets/train/preprocess_workers:
  desc: null
  value: 4
data/datamodule/datasets/val:
  desc: null
  value:
  - _target_: cdvae.pl_data.dataset.CrystDataset
    name: Formation energy val
    path: C:\Users\GrzegorzKaszuba\PycharmProjects\cdvae-main/data/perov_5/val.csv
    prop: heat_ref
    niggli: true
    primitive: false
    graph_method: crystalnn
    lattice_scale_method: scale_length
    preprocess_workers: 4
data/datamodule/datasets/test:
  desc: null
  value:
  - _target_: cdvae.pl_data.dataset.CrystDataset
    name: Formation energy test
    path: C:\Users\GrzegorzKaszuba\PycharmProjects\cdvae-main/data/perov_5/test.csv
    prop: heat_ref
    niggli: true
    primitive: false
    graph_method: crystalnn
    lattice_scale_method: scale_length
    preprocess_workers: 4
data/datamodule/num_workers/train:
  desc: null
  value: 0
data/datamodule/num_workers/val:
  desc: null
  value: 0
data/datamodule/num_workers/test:
  desc: null
  value: 0
data/datamodule/batch_size/train:
  desc: null
  value: 32
data/datamodule/batch_size/val:
  desc: null
  value: 32
data/datamodule/batch_size/test:
  desc: null
  value: 32
logging/val_check_interval:
  desc: null
  value: 5
logging/progress_bar_refresh_rate:
  desc: null
  value: 20
logging/wandb/name:
  desc: null
  value: perov
logging/wandb/project:
  desc: null
  value: crystal_generation_mit
logging/wandb/entity:
  desc: null
  value: None
logging/wandb/log_model:
  desc: null
  value: true
logging/wandb/mode:
  desc: null
  value: online
logging/wandb/group:
  desc: null
  value: perov
logging/wandb_watch/log:
  desc: null
  value: all
logging/wandb_watch/log_freq:
  desc: null
  value: 500
logging/lr_monitor/logging_interval:
  desc: null
  value: step
logging/lr_monitor/log_momentum:
  desc: null
  value: false
model/encoder/_target_:
  desc: null
  value: cdvae.pl_modules.gnn.DimeNetPlusPlusWrap
model/encoder/num_targets:
  desc: null
  value: 1
model/encoder/hidden_channels:
  desc: null
  value: 128
model/encoder/num_blocks:
  desc: null
  value: 4
model/encoder/int_emb_size:
  desc: null
  value: 64
model/encoder/basis_emb_size:
  desc: null
  value: 8
model/encoder/out_emb_channels:
  desc: null
  value: 256
model/encoder/num_spherical:
  desc: null
  value: 7
model/encoder/num_radial:
  desc: null
  value: 6
model/encoder/otf_graph:
  desc: null
  value: false
model/encoder/cutoff:
  desc: null
  value: 7.0
model/encoder/max_num_neighbors:
  desc: null
  value: 20
model/encoder/envelope_exponent:
  desc: null
  value: 5
model/encoder/num_before_skip:
  desc: null
  value: 1
model/encoder/num_after_skip:
  desc: null
  value: 2
model/encoder/num_output_layers:
  desc: null
  value: 3
model/encoder/readout:
  desc: null
  value: mean
model/decoder/_target_:
  desc: null
  value: cdvae.pl_modules.decoder.GemNetTDecoder
model/decoder/hidden_dim:
  desc: null
  value: 128
model/decoder/latent_dim:
  desc: null
  value: 256
model/decoder/max_neighbors:
  desc: null
  value: 20
model/decoder/radius:
  desc: null
  value: 7.0
model/decoder/scale_file:
  desc: null
  value: C:\Users\GrzegorzKaszuba\PycharmProjects\cdvae-main/cdvae/pl_modules/gemnet/gemnet-dT.json
model/_target_:
  desc: null
  value: cdvae.pl_modules.model.CDVAE
model/hidden_dim:
  desc: null
  value: 256
model/latent_dim:
  desc: null
  value: 256
model/fc_num_layers:
  desc: null
  value: 1
model/max_atoms:
  desc: null
  value: 20
model/cost_natom:
  desc: null
  value: 1.0
model/cost_coord:
  desc: null
  value: 10.0
model/cost_type:
  desc: null
  value: 1.0
model/cost_lattice:
  desc: null
  value: 10.0
model/cost_composition:
  desc: null
  value: 1.0
model/cost_edge:
  desc: null
  value: 10.0
model/cost_property:
  desc: null
  value: 1.0
model/beta:
  desc: null
  value: 0.01
model/teacher_forcing_lattice:
  desc: null
  value: true
model/teacher_forcing_max_epoch:
  desc: null
  value: 1500
model/max_neighbors:
  desc: null
  value: 20
model/radius:
  desc: null
  value: 7.0
model/sigma_begin:
  desc: null
  value: 10.0
model/sigma_end:
  desc: null
  value: 0.01
model/type_sigma_begin:
  desc: null
  value: 5.0
model/type_sigma_end:
  desc: null
  value: 0.01
model/num_noise_level:
  desc: null
  value: 50
model/predict_property:
  desc: null
  value: false
optim/optimizer/_target_:
  desc: null
  value: torch.optim.Adam
optim/optimizer/lr:
  desc: null
  value: 0.001
optim/optimizer/betas:
  desc: null
  value:
  - 0.9
  - 0.999
optim/optimizer/eps:
  desc: null
  value: 1.0e-08
optim/optimizer/weight_decay:
  desc: null
  value: 0
optim/use_lr_scheduler:
  desc: null
  value: true
optim/lr_scheduler/_target_:
  desc: null
  value: torch.optim.lr_scheduler.ReduceLROnPlateau
optim/lr_scheduler/factor:
  desc: null
  value: 0.6
optim/lr_scheduler/patience:
  desc: null
  value: 30
optim/lr_scheduler/min_lr:
  desc: null
  value: 0.0001
train/deterministic:
  desc: null
  value: false
train/random_seed:
  desc: null
  value: 42
train/pl_trainer/fast_dev_run:
  desc: null
  value: false
train/pl_trainer/gpus:
  desc: null
  value: 1
train/pl_trainer/precision:
  desc: null
  value: 32
train/pl_trainer/max_epochs:
  desc: null
  value: 5
train/pl_trainer/accumulate_grad_batches:
  desc: null
  value: 1
train/pl_trainer/num_sanity_val_steps:
  desc: null
  value: 2
train/pl_trainer/gradient_clip_val:
  desc: null
  value: 0.5
train/pl_trainer/gradient_clip_algorithm:
  desc: null
  value: value
train/pl_trainer/profiler:
  desc: null
  value: simple
train/monitor_metric:
  desc: null
  value: train_loss
train/monitor_metric_mode:
  desc: null
  value: min
train/early_stopping/patience:
  desc: null
  value: 100000
train/early_stopping/verbose:
  desc: null
  value: false
train/model_checkpoints/save_top_k:
  desc: null
  value: 1
train/model_checkpoints/verbose:
  desc: null
  value: false
expname:
  desc: null
  value: perov
core/version:
  desc: null
  value: 0.0.1
core/tags:
  desc: null
  value:
  - '2023-05-11'
HYDRA_FULL_ERROR:
  desc: null
  value: 1
stats/params_total:
  desc: null
  value: 4920414
stats/params_trainable:
  desc: null
  value: 4920297
stats/params_not_trainable:
  desc: null
  value: 117
